In [1]:
from numpy import *

arr = array([1,2,3,4,5])

arr = arr + 5
print(arr)

[ 6  7  8  9 10]


In [7]:
arr = array([4,5,6,7,8])

for i in arr:
    print(i+5, " " , end ="")

9  10  11  12  13  

In [8]:
arr = array([4,5,6,7,8])

for i in arr:
    print(i+5)

9
10
11
12
13


In [10]:
arr1 = array([1,2,3,4,5])
arr2 = array([4,5,6,7,8])

arr3 = arr1 + arr2
print(arr3)

[ 5  7  9 11 13]


In [15]:
arr =  array([0,1,2,3,4])

print(sin(arr))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [14]:
arr = array([1,2,3,4])
print(log(arr))

[0.         0.69314718 1.09861229 1.38629436]


In [16]:
arr = array([1,2,3,4])
print(sqrt(arr))

[1.         1.41421356 1.73205081 2.        ]


In [17]:
arr = array([1,2,3,4])
print(sum(arr))

10


In [18]:
arr = array([1,2,3,4])
print(min(arr))

1


In [19]:
arr = array([1,2,3,4])
print(max(arr))

4


In [20]:
arr = array([12,2,30,4])
print(sort(arr))

[ 2  4 12 30]


In [21]:
arr = array([1,2,3,4])
print(unique(arr))

[1 2 3 4]


In [23]:
arr1 = array([1,2,3,4,5])
arr2 = array([6,7,8,9,10])
print(concatenate([arr1,arr2]))

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
arr = array([5,8,9,6,3])

arr1 = arr
print(arr)
print(arr1)

print(id(arr))
print(id(arr1))

[5 8 9 6 3]
[5 8 9 6 3]
36419768
36419768


In [26]:
arr = array([5,8,9,6,3])

arr1 = arr.view()
print(arr)
print(arr1)

print(id(arr))
print(id(arr1))

[5 8 9 6 3]
[5 8 9 6 3]
36367720
36367560


In [27]:
# shallow copy
arr = array([5,8,9,6,3])

arr1 = arr

arr[1] = 7

print(arr)
print(arr1)

print(id(arr))
print(id(arr1))

[5 7 9 6 3]
[5 7 9 6 3]
36366880
36366880


In [28]:
# deep copy
arr = array([5,8,9,6,3])

arr1 = arr.copy()

arr[1] = 7

print(arr)
print(arr1)

print(id(arr))
print(id(arr1))

[5 7 9 6 3]
[5 8 9 6 3]
36365960
36366400
