In [6]:
from numpy import *

arr = array([
              [1,2,3],
              [4,5,6]
])

print(arr, "\n")
print(arr.ndim, "\n")
print(arr.shape, "\n")
print(arr.size)

[[1 2 3]
 [4 5 6]] 

2 

(2, 3) 

6


In [7]:
from numpy import *

arr = array([
              [1,2,3],
              [4,5,6]
])

arr1 = arr.flatten() # convert 2D array to 1D array
print(arr1)

[1 2 3 4 5 6]


In [12]:
from numpy import *

arr = array([
              [1,2,3,6,7,8],
              [4,5,6,7,9,8]
])

arr1 = arr.flatten() # convert 2D array to 1D array
print(arr1)

arr2 = arr1.reshape(3,4)
print(arr2)

[1 2 3 6 7 8 4 5 6 7 9 8]
[[1 2 3 6]
 [7 8 4 5]
 [6 7 9 8]]


In [14]:
from numpy import *

arr = array([
              [1,2,3,6,7,8],
              [4,5,6,7,9,8]
])
arr1 = arr.reshape(4,3)
print(arr1)

[[1 2 3]
 [6 7 8]
 [4 5 6]
 [7 9 8]]


In [17]:
from numpy import *

arr = array([
              [1,2,3,6,7,8],
              [4,5,6,7,9,8]
])
arr1 = arr.reshape(2,2,3)
print(arr1)

[[[1 2 3]
  [6 7 8]]

 [[4 5 6]
  [7 9 8]]]


In [19]:
from numpy import *

arr = array([
              [1,2,3,6],
              [4,5,6,7]
])

m = matrix(arr)
print(m)

[[1 2 3 6]
 [4 5 6 7]]


In [20]:
from numpy import *

m = matrix('1 2 3 6 ; 4 5 6 7')

print(m)

[[1 2 3 6]
 [4 5 6 7]]


In [21]:
from numpy import *

m = matrix('1 2 ; 3 6 ; 4 5 ; 6 7')

print(m)

[[1 2]
 [3 6]
 [4 5]
 [6 7]]


In [26]:
from numpy import *

m = matrix('1 2 3 ; 6  4 5 ; 8 6 7')

print(m)
print(diagonal(m))
print(m.min())
print(m.max())

[[1 2 3]
 [6 4 5]
 [8 6 7]]
[1 4 7]
1
8


In [29]:
from numpy import *

m1 = matrix('1 2 3 ; 6 4 5 ; 8 6 7')
m2 = matrix('8 9 6 ; 4 5 3 ; 1 7 2')

m3 = m1 + m2
m4 = m1 * m2    # In matrix we don't need to code that much for multiplication bcoz it have function for that
print(m3)
print(m4)  

[[ 9 11  9]
 [10  9  8]
 [ 9 13  9]]
[[ 19  40  18]
 [ 69 109  58]
 [ 95 151  80]]
