In [16]:
#from array import *   ------------not support multidimenstion array------------
from numpy import *
arr = array([1, 2, 3, 5, 7])

print(arr)

[1 2 3 5 7]


In [19]:
from numpy import *
arr = array([[1, 2, 3], [4, 5, 7]])

print(arr)

[[1 2 3]
 [4 5 7]]


In [24]:
from numpy import *
arr = array([1, 2, 3, 4, 5])

print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [25]:
from numpy import *
arr = array([1, 2, 3, 4, 5.4])

print(arr)
print(arr.dtype)

[1.  2.  3.  4.  5.4]
float64


In [26]:
from numpy import *
arr = array([1, 2, 3, 4, 5],float)

print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [27]:
from numpy import *
arr = array([1, 2, 3, 4, 5.4],int)

print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [31]:
from numpy import *
arr = linspace(0,15,16)    # linspace(start, end, steps(no. of part of given range))

print(arr)
print(arr.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
float64


In [32]:
from numpy import *
arr = linspace(0, 15, 10)

print(arr)
print(arr.dtype)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.         11.66666667 13.33333333 15.        ]
float64


In [37]:
from numpy import *
arr = logspace(1, 40, 6)

print(arr)
print(arr.dtype)

[1.00000000e+01 6.30957344e+08 3.98107171e+16 2.51188643e+24
 1.58489319e+32 1.00000000e+40]
float64


In [38]:
from numpy import *
arr = logspace(1, 40, 6)

print('%.2f' %arr[4])
print(arr.dtype)

158489319246112378845787548811264.00
float64


In [36]:
from numpy import *
arr = arange(1, 15, 2)    # arrange(start, end, it's a no. skip in range)

print(arr)
print(arr.dtype)

[ 1  3  5  7  9 11 13]
int32


In [39]:
from numpy import *
arr = zeros(5)

print(arr)
print(arr.dtype)

[0. 0. 0. 0. 0.]
float64


In [40]:
from numpy import *
arr = ones(5)

print(arr)
print(arr.dtype)

[1. 1. 1. 1. 1.]
float64


In [2]:
from numpy import *
arr = zeros(5, int)

print(arr)
print(arr.dtype)

[0 0 0 0 0]
int32


In [3]:
from numpy import *
arr = ones(5, int)

print(arr)
print(arr.dtype)

[1 1 1 1 1]
int32
